import React, { useEffect, useState } from 'react';
import { explorerUrl, truncateAddress, CLUSTER } from '@/lib/solana';

/**
 * GovernanceBadge — displays the 5 Squads v4 multisigs governing DPO2U.
 *
 * Source: /squads-config.json deployed alongside the static landing assets
 * (generated by `scripts/setup-squads-multisig.ts`). If the file is absent
 * (pre-migration), the component renders nothing — landing degrades cleanly.
 *
 * See /root/dpo2u-solana/docs/GOVERNANCE.md for threshold/time-lock rationale.
 */

interface MultisigEntry {
  role: string;
  description: string;
  threshold: string;
  timeLockSeconds: number;
  multisigPda: string;
  vaultPda: string;
}

interface SquadsConfig {
  cluster: string;
  multisigs: MultisigEntry[];
}

function fmtTimeLock(sec: number): string {
  if (sec === 0) return 'no time-lock';
  if (sec >= 86400) return `${sec / 86400}h time-lock`;
  if (sec >= 3600) return `${sec / 3600}h time-lock`;
  return `${sec}s time-lock`;
}

export default function GovernanceBadge() {
  const [config, setConfig] = useState<SquadsConfig | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch('/squads-config.json', { cache: 'no-cache' })
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json();
      })
      .then((data: SquadsConfig) => setConfig(data))
      .catch((err: Error) => setError(err.message));
  }, []);

  if (error || !config || !config.multisigs?.length) {
    return null;
  }

  return (
    <section
      style={{
        padding: '32px 0',
        borderTop: '.5px solid rgba(0,0,0,.12)',
        borderBottom: '.5px solid rgba(0,0,0,.12)',
        margin: '32px 0',
      }}
    >
      <p
        style={{
          fontFamily: 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
          fontSize: 11,
          letterSpacing: '.18em',
          textTransform: 'uppercase',
          color: 'rgba(0,0,0,.55)',
          margin: '0 0 16px',
        }}
      >
        § GOVERNANCE — SQUADS v4 MULTISIG ({config.cluster})
      </p>
      <h3
        style={{
          fontFamily: 'Georgia, "Times New Roman", serif',
          fontSize: 24,
          lineHeight: 1.2,
          fontWeight: 500,
          margin: '0 0 8px',
        }}
      >
        Five multisigs. Five jurisdictions of trust.
      </h3>
      <p
        style={{
          fontFamily: 'system-ui, -apple-system, sans-serif',
          fontSize: 14,
          lineHeight: 1.55,
          color: 'rgba(0,0,0,.7)',
          margin: '0 0 24px',
          maxWidth: 640,
        }}
      >
        DPO2U program upgrades, MiCAR reserve management, compressed
        attestation revokes, and treasury operations are all governed by
        independent Squads v4 multisigs with role-specific thresholds and
        time-locks. No single keypair can act unilaterally. Every proposal
        is on-chain and observable before it executes.
      </p>
      <div
        style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
          gap: 16,
        }}
      >
        {config.multisigs.map((m) => (
          <a
            key={m.multisigPda}
            href={explorerUrl(m.multisigPda)}
            target="_blank"
            rel="noopener noreferrer"
            style={{
              display: 'block',
              padding: 16,
              border: '.5px solid rgba(0,0,0,.18)',
              textDecoration: 'none',
              color: 'inherit',
              background: 'rgba(255,255,255,.5)',
            }}
          >
            <div
              style={{
                fontFamily: 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
                fontSize: 10,
                letterSpacing: '.15em',
                textTransform: 'uppercase',
                color: 'rgba(0,0,0,.55)',
                marginBottom: 6,
              }}
            >
              [{config.multisigs.indexOf(m)}] {m.role}
            </div>
            <div
              style={{
                fontFamily: 'Georgia, "Times New Roman", serif',
                fontSize: 16,
                fontWeight: 500,
                lineHeight: 1.3,
                marginBottom: 8,
              }}
            >
              {m.description}
            </div>
            <div
              style={{
                fontFamily: 'system-ui, -apple-system, sans-serif',
                fontSize: 12,
                color: 'rgba(0,0,0,.65)',
                marginBottom: 6,
              }}
            >
              {m.threshold} · {fmtTimeLock(m.timeLockSeconds)}
            </div>
            <div
              style={{
                fontFamily: 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
                fontSize: 11,
                color: 'rgba(0,0,0,.55)',
              }}
            >
              {truncateAddress(m.multisigPda)}
            </div>
          </a>
        ))}
      </div>
      <p
        style={{
          fontFamily: 'ui-monospace, "SF Mono", Menlo, Consolas, monospace',
          fontSize: 10,
          letterSpacing: '.08em',
          color: 'rgba(0,0,0,.5)',
          marginTop: 16,
        }}
      >
        — Squads v4 program: SQDS4ej4dZndYAQiRJzRZqDPoAHTQ8R7BbfwL3GnxCk · cluster: {CLUSTER} —
      </p>
    </section>
  );
}
